### ISSUE TITLE
I can't seem to get it to work

### ISSUE THREAD

**Issue by Username13211** [smoak/jackbox-bot#2]
Am I supposed to edit the files and manually add the room code there? or is it just number/letter accordingly?

**Comment by smoak** [comment]
Can you provide more information? What isn't working? Are you getting any errors? How are you trying to run the bot? Have you seen the README?

```bash
export JACKBOX_ROOMID=[ENTER ROOM ID HERE]
bundle exec ruby bot.rb 
```
